//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rxApi.Models.EMRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugs
    {
        public int Did { get; set; }
        public string DName { get; set; }
        public Nullable<int> Dstatus { get; set; }
        public string DType { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string ConDisease { get; set; }
    }
}
