//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rxApi.Models.EMRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public string username { get; set; }
        public string password { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<double> lat { get; set; }
        public Nullable<double> @long { get; set; }
        public string disease { get; set; }
    }
}
