//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rxApi.Models.EMRModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RxHaveDrugs
    {
        public int id { get; set; }
        public Nullable<int> rxidFK { get; set; }
        public string company { get; set; }
        public string method { get; set; }
        public string drugs { get; set; }
        public string Note { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
